package com.medev.modules.ai.service;

import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.medev.modules.ai.dto.AiOnboardingRequest;
import com.medev.modules.ai.dto.AiOnboardingResponse;
import com.medev.modules.ai.model.LlmException;
import com.medev.modules.profile.entity.Experience;
import com.medev.modules.profile.entity.Profile;
import com.medev.modules.profile.entity.Skill;
import com.medev.modules.profile.repository.ExperienceRepository;
import com.medev.modules.profile.repository.ProfileRepository;
import com.medev.modules.profile.repository.SkillRepository;
import com.medev.shared.exception.NotFoundException;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

@Slf4j
@Service
@RequiredArgsConstructor
public class AiOnboardingService {

    private final LlmProvider llmProvider;
    private final PromptLoader promptLoader;
    private final ObjectMapper objectMapper;
    private final ProfileRepository profileRepository;
    private final SkillRepository skillRepository;
    private final ExperienceRepository experienceRepository;

    @Transactional
    public AiOnboardingResponse generateAndSaveProfile(Long userId, AiOnboardingRequest request) {
        String systemPrompt = promptLoader.load("onboarding_wizard_v1");
        
        String userMessage = String.format("""
                Role: %s
                Stack: %s
                Recent Experience: %s
                """, request.getRole(), request.getStack(), request.getRecentExperience());

        String jsonResponse = llmProvider.structuredCompletion(systemPrompt, userMessage);
        
        AiOnboardingResponse response;
        try {
            response = objectMapper.readValue(jsonResponse, AiOnboardingResponse.class);
        } catch (JsonProcessingException e) {
            log.error("Failed to parse JSON from LLM: {}", jsonResponse);
            throw new LlmException(LlmException.Reason.INVALID_RESPONSE, "Invalid JSON format from AI");
        }

        // Save to Database
        Profile profile = profileRepository.findByUserId(userId)
                .orElseThrow(() -> new NotFoundException("Profile not found"));

        if (profile.getSummary() == null || profile.getSummary().isEmpty()) {
            profile.setSummary(response.getBio());
        }
        if (profile.getHeadline() == null || profile.getHeadline().isEmpty()) {
            profile.setHeadline(response.getHeadline());
        }
        profileRepository.save(profile);

        // Delete old skills generated by onboarding (or just add new ones)
        if (response.getSkills() != null) {
            for (AiOnboardingResponse.SkillDto s : response.getSkills()) {
                Skill skill = Skill.builder()
                        .profile(profile)
                        .name(s.getName())
                        .category(s.getCategory())
                        .build();
                skillRepository.save(skill);
            }
        }

        if (response.getExperiences() != null) {
            for (AiOnboardingResponse.ExperienceDto exp : response.getExperiences()) {
                Experience experience = Experience.builder()
                        .profile(profile)
                        .company(exp.getCompany())
                        .position(exp.getPosition())
                        .description(exp.getDescription())
                        // set placeholders for dates as they aren't provided by user directly
                        .startDate(java.time.LocalDate.now().minusYears(1))
                        .endDate(null)
                        .build();
                experienceRepository.save(experience);
            }
        }

        return response;
    }
}
