spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
  flyway:
    enabled: true
    locations: classpath:db/migration
  security:
    user:
      name: user
      password: stub_password_to_suppress_log

server:
  port: 8080
  servlet:
    context-path: /api

jwt:
  expiration: 86400000            # 24 часа
  refresh-expiration: 2592000000  # 30 дней

github:
  api-url: https://api.github.com

